# Generated by Django 4.0.5 on 2022-08-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_myapp_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myapp.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
