# Generated by Django 4.0.5 on 2022-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_myapp_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
